/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ParentRating {
  'review' : string,
  'date' : Time,
  'rating' : bigint,
}
export interface PaymentEntry {
  'date' : Time,
  'paymentMode' : PaymentMode,
  'receiptNo' : bigint,
  'amount' : bigint,
}
export type PaymentMode = { 'bhim' : null } |
  { 'cash' : null } |
  { 'googlePay' : null } |
  { 'phonePe' : null };
export type StudentClass = { 'grade1' : null } |
  { 'grade2' : null } |
  { 'grade3' : null } |
  { 'grade4' : null } |
  { 'grade5' : null } |
  { 'grade6' : null } |
  { 'grade7' : null } |
  { 'juniorKindergarten' : null } |
  { 'nursery' : null } |
  { 'seniorKindergarten' : null };
export interface StudentProfile {
  'id' : bigint,
  'status' : StudentStatus,
  'payments' : Array<PaymentEntry>,
  'motherPhoneNumber' : string,
  'name' : string,
  'ratings' : Array<ParentRating>,
  'surname' : string,
  'isArchived' : boolean,
  'email' : [] | [string],
  'totalFee' : bigint,
  'fatherPhoneNumber' : string,
  'studentClass' : StudentClass,
  'parentName' : string,
}
export type StudentStatus = { 'complete' : null } |
  { 'incompleteProfile' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addParentRating' : ActorMethod<[bigint, bigint, string], undefined>,
  'addPayment' : ActorMethod<[bigint, PaymentEntry], bigint>,
  'addPendingStudent' : ActorMethod<[StudentProfile], undefined>,
  'addStudent' : ActorMethod<[StudentProfile], undefined>,
  'archiveStudent' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllPendingStudents' : ActorMethod<[], Array<StudentProfile>>,
  'getAllStudents' : ActorMethod<[], Array<StudentProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getStudent' : ActorMethod<[bigint], StudentProfile>,
  'getStudentRatings' : ActorMethod<[bigint], Array<ParentRating>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'makeStudentDataPersistent' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePendingStudent' : ActorMethod<[StudentProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];