/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const PaymentMode = IDL.Variant({
  'bhim' : IDL.Null,
  'cash' : IDL.Null,
  'googlePay' : IDL.Null,
  'phonePe' : IDL.Null,
});
export const PaymentEntry = IDL.Record({
  'date' : Time,
  'paymentMode' : PaymentMode,
  'receiptNo' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const StudentStatus = IDL.Variant({
  'complete' : IDL.Null,
  'incompleteProfile' : IDL.Null,
});
export const ParentRating = IDL.Record({
  'review' : IDL.Text,
  'date' : Time,
  'rating' : IDL.Nat,
});
export const StudentClass = IDL.Variant({
  'grade1' : IDL.Null,
  'grade2' : IDL.Null,
  'grade3' : IDL.Null,
  'grade4' : IDL.Null,
  'grade5' : IDL.Null,
  'grade6' : IDL.Null,
  'grade7' : IDL.Null,
  'juniorKindergarten' : IDL.Null,
  'nursery' : IDL.Null,
  'seniorKindergarten' : IDL.Null,
});
export const StudentProfile = IDL.Record({
  'id' : IDL.Nat,
  'status' : StudentStatus,
  'payments' : IDL.Vec(PaymentEntry),
  'motherPhoneNumber' : IDL.Text,
  'name' : IDL.Text,
  'ratings' : IDL.Vec(ParentRating),
  'surname' : IDL.Text,
  'isArchived' : IDL.Bool,
  'email' : IDL.Opt(IDL.Text),
  'totalFee' : IDL.Nat,
  'fatherPhoneNumber' : IDL.Text,
  'studentClass' : StudentClass,
  'parentName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addParentRating' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'addPayment' : IDL.Func([IDL.Nat, PaymentEntry], [IDL.Nat], []),
  'addPendingStudent' : IDL.Func([StudentProfile], [], []),
  'addStudent' : IDL.Func([StudentProfile], [], []),
  'archiveStudent' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllPendingStudents' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getStudent' : IDL.Func([IDL.Nat], [StudentProfile], ['query']),
  'getStudentRatings' : IDL.Func([IDL.Nat], [IDL.Vec(ParentRating)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'makeStudentDataPersistent' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePendingStudent' : IDL.Func([StudentProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const PaymentMode = IDL.Variant({
    'bhim' : IDL.Null,
    'cash' : IDL.Null,
    'googlePay' : IDL.Null,
    'phonePe' : IDL.Null,
  });
  const PaymentEntry = IDL.Record({
    'date' : Time,
    'paymentMode' : PaymentMode,
    'receiptNo' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const StudentStatus = IDL.Variant({
    'complete' : IDL.Null,
    'incompleteProfile' : IDL.Null,
  });
  const ParentRating = IDL.Record({
    'review' : IDL.Text,
    'date' : Time,
    'rating' : IDL.Nat,
  });
  const StudentClass = IDL.Variant({
    'grade1' : IDL.Null,
    'grade2' : IDL.Null,
    'grade3' : IDL.Null,
    'grade4' : IDL.Null,
    'grade5' : IDL.Null,
    'grade6' : IDL.Null,
    'grade7' : IDL.Null,
    'juniorKindergarten' : IDL.Null,
    'nursery' : IDL.Null,
    'seniorKindergarten' : IDL.Null,
  });
  const StudentProfile = IDL.Record({
    'id' : IDL.Nat,
    'status' : StudentStatus,
    'payments' : IDL.Vec(PaymentEntry),
    'motherPhoneNumber' : IDL.Text,
    'name' : IDL.Text,
    'ratings' : IDL.Vec(ParentRating),
    'surname' : IDL.Text,
    'isArchived' : IDL.Bool,
    'email' : IDL.Opt(IDL.Text),
    'totalFee' : IDL.Nat,
    'fatherPhoneNumber' : IDL.Text,
    'studentClass' : StudentClass,
    'parentName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addParentRating' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'addPayment' : IDL.Func([IDL.Nat, PaymentEntry], [IDL.Nat], []),
    'addPendingStudent' : IDL.Func([StudentProfile], [], []),
    'addStudent' : IDL.Func([StudentProfile], [], []),
    'archiveStudent' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllPendingStudents' : IDL.Func(
        [],
        [IDL.Vec(StudentProfile)],
        ['query'],
      ),
    'getAllStudents' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getStudent' : IDL.Func([IDL.Nat], [StudentProfile], ['query']),
    'getStudentRatings' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ParentRating)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'makeStudentDataPersistent' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePendingStudent' : IDL.Func([StudentProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };