/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StudentProfile {
    id: bigint;
    status: StudentStatus;
    payments: Array<PaymentEntry>;
    motherPhoneNumber: string;
    name: string;
    ratings: Array<ParentRating>;
    surname: string;
    isArchived: boolean;
    email?: string;
    totalFee: bigint;
    fatherPhoneNumber: string;
    studentClass: StudentClass;
    parentName: string;
}
export type Time = bigint;
export interface PaymentEntry {
    date: Time;
    paymentMode: PaymentMode;
    receiptNo: bigint;
    amount: bigint;
}
export interface ParentRating {
    review: string;
    date: Time;
    rating: bigint;
}
export interface UserProfile {
    name: string;
    role: string;
}
export enum PaymentMode {
    bhim = "bhim",
    cash = "cash",
    googlePay = "googlePay",
    phonePe = "phonePe"
}
export enum StudentClass {
    grade1 = "grade1",
    grade2 = "grade2",
    grade3 = "grade3",
    grade4 = "grade4",
    grade5 = "grade5",
    grade6 = "grade6",
    grade7 = "grade7",
    juniorKindergarten = "juniorKindergarten",
    nursery = "nursery",
    seniorKindergarten = "seniorKindergarten"
}
export enum StudentStatus {
    complete = "complete",
    incompleteProfile = "incompleteProfile"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addParentRating(studentId: bigint, rating: bigint, review: string): Promise<void>;
    addPayment(studentId: bigint, payment: PaymentEntry): Promise<bigint>;
    addPendingStudent(profile: StudentProfile): Promise<void>;
    addStudent(profile: StudentProfile): Promise<void>;
    archiveStudent(studentId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllPendingStudents(): Promise<Array<StudentProfile>>;
    getAllStudents(): Promise<Array<StudentProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getStudent(studentId: bigint): Promise<StudentProfile>;
    getStudentRatings(studentId: bigint): Promise<Array<ParentRating>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    makeStudentDataPersistent(profileId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updatePendingStudent(profile: StudentProfile): Promise<void>;
}
import type { ParentRating as _ParentRating, PaymentEntry as _PaymentEntry, PaymentMode as _PaymentMode, StudentClass as _StudentClass, StudentProfile as _StudentProfile, StudentStatus as _StudentStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addParentRating(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addParentRating(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addParentRating(arg0, arg1, arg2);
            return result;
        }
    }
    async addPayment(arg0: bigint, arg1: PaymentEntry): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPayment(arg0, to_candid_PaymentEntry_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPayment(arg0, to_candid_PaymentEntry_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addPendingStudent(arg0: StudentProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPendingStudent(to_candid_StudentProfile_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPendingStudent(to_candid_StudentProfile_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addStudent(arg0: StudentProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudent(to_candid_StudentProfile_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudent(to_candid_StudentProfile_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async archiveStudent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.archiveStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.archiveStudent(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllPendingStudents(): Promise<Array<StudentProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPendingStudents();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPendingStudents();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStudents(): Promise<Array<StudentProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: bigint): Promise<StudentProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_StudentProfile_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_StudentProfile_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentRatings(arg0: bigint): Promise<Array<ParentRating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentRatings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentRatings(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async makeStudentDataPersistent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.makeStudentDataPersistent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.makeStudentDataPersistent(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updatePendingStudent(arg0: StudentProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePendingStudent(to_candid_StudentProfile_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePendingStudent(to_candid_StudentProfile_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_PaymentEntry_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentEntry): PaymentEntry {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMode_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMode): PaymentMode {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_StudentClass_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentClass): StudentClass {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_StudentProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentProfile): StudentProfile {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_StudentStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentStatus): StudentStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _StudentStatus;
    payments: Array<_PaymentEntry>;
    motherPhoneNumber: string;
    name: string;
    ratings: Array<_ParentRating>;
    surname: string;
    isArchived: boolean;
    email: [] | [string];
    totalFee: bigint;
    fatherPhoneNumber: string;
    studentClass: _StudentClass;
    parentName: string;
}): {
    id: bigint;
    status: StudentStatus;
    payments: Array<PaymentEntry>;
    motherPhoneNumber: string;
    name: string;
    ratings: Array<ParentRating>;
    surname: string;
    isArchived: boolean;
    email?: string;
    totalFee: bigint;
    fatherPhoneNumber: string;
    studentClass: StudentClass;
    parentName: string;
} {
    return {
        id: value.id,
        status: from_candid_StudentStatus_n17(_uploadFile, _downloadFile, value.status),
        payments: from_candid_vec_n19(_uploadFile, _downloadFile, value.payments),
        motherPhoneNumber: value.motherPhoneNumber,
        name: value.name,
        ratings: value.ratings,
        surname: value.surname,
        isArchived: value.isArchived,
        email: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.email)),
        totalFee: value.totalFee,
        fatherPhoneNumber: value.fatherPhoneNumber,
        studentClass: from_candid_StudentClass_n25(_uploadFile, _downloadFile, value.studentClass),
        parentName: value.parentName
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: _Time;
    paymentMode: _PaymentMode;
    receiptNo: bigint;
    amount: bigint;
}): {
    date: Time;
    paymentMode: PaymentMode;
    receiptNo: bigint;
    amount: bigint;
} {
    return {
        date: value.date,
        paymentMode: from_candid_PaymentMode_n22(_uploadFile, _downloadFile, value.paymentMode),
        receiptNo: value.receiptNo,
        amount: value.amount
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    complete: null;
} | {
    incompleteProfile: null;
}): StudentStatus {
    return "complete" in value ? StudentStatus.complete : "incompleteProfile" in value ? StudentStatus.incompleteProfile : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bhim: null;
} | {
    cash: null;
} | {
    googlePay: null;
} | {
    phonePe: null;
}): PaymentMode {
    return "bhim" in value ? PaymentMode.bhim : "cash" in value ? PaymentMode.cash : "googlePay" in value ? PaymentMode.googlePay : "phonePe" in value ? PaymentMode.phonePe : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    grade1: null;
} | {
    grade2: null;
} | {
    grade3: null;
} | {
    grade4: null;
} | {
    grade5: null;
} | {
    grade6: null;
} | {
    grade7: null;
} | {
    juniorKindergarten: null;
} | {
    nursery: null;
} | {
    seniorKindergarten: null;
}): StudentClass {
    return "grade1" in value ? StudentClass.grade1 : "grade2" in value ? StudentClass.grade2 : "grade3" in value ? StudentClass.grade3 : "grade4" in value ? StudentClass.grade4 : "grade5" in value ? StudentClass.grade5 : "grade6" in value ? StudentClass.grade6 : "grade7" in value ? StudentClass.grade7 : "juniorKindergarten" in value ? StudentClass.juniorKindergarten : "nursery" in value ? StudentClass.nursery : "seniorKindergarten" in value ? StudentClass.seniorKindergarten : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudentProfile>): Array<StudentProfile> {
    return value.map((x)=>from_candid_StudentProfile_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentEntry>): Array<PaymentEntry> {
    return value.map((x)=>from_candid_PaymentEntry_n20(_uploadFile, _downloadFile, x));
}
function to_candid_PaymentEntry_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentEntry): _PaymentEntry {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMode_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): _PaymentMode {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_StudentClass_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentClass): _StudentClass {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_StudentProfile_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentProfile): _StudentProfile {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_StudentStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentStatus): _StudentStatus {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: Time;
    paymentMode: PaymentMode;
    receiptNo: bigint;
    amount: bigint;
}): {
    date: _Time;
    paymentMode: _PaymentMode;
    receiptNo: bigint;
    amount: bigint;
} {
    return {
        date: value.date,
        paymentMode: to_candid_PaymentMode_n3(_uploadFile, _downloadFile, value.paymentMode),
        receiptNo: value.receiptNo,
        amount: value.amount
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: StudentStatus;
    payments: Array<PaymentEntry>;
    motherPhoneNumber: string;
    name: string;
    ratings: Array<ParentRating>;
    surname: string;
    isArchived: boolean;
    email?: string;
    totalFee: bigint;
    fatherPhoneNumber: string;
    studentClass: StudentClass;
    parentName: string;
}): {
    id: bigint;
    status: _StudentStatus;
    payments: Array<_PaymentEntry>;
    motherPhoneNumber: string;
    name: string;
    ratings: Array<_ParentRating>;
    surname: string;
    isArchived: boolean;
    email: [] | [string];
    totalFee: bigint;
    fatherPhoneNumber: string;
    studentClass: _StudentClass;
    parentName: string;
} {
    return {
        id: value.id,
        status: to_candid_StudentStatus_n7(_uploadFile, _downloadFile, value.status),
        payments: to_candid_vec_n9(_uploadFile, _downloadFile, value.payments),
        motherPhoneNumber: value.motherPhoneNumber,
        name: value.name,
        ratings: value.ratings,
        surname: value.surname,
        isArchived: value.isArchived,
        email: value.email ? candid_some(value.email) : candid_none(),
        totalFee: value.totalFee,
        fatherPhoneNumber: value.fatherPhoneNumber,
        studentClass: to_candid_StudentClass_n10(_uploadFile, _downloadFile, value.studentClass),
        parentName: value.parentName
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentClass): {
    grade1: null;
} | {
    grade2: null;
} | {
    grade3: null;
} | {
    grade4: null;
} | {
    grade5: null;
} | {
    grade6: null;
} | {
    grade7: null;
} | {
    juniorKindergarten: null;
} | {
    nursery: null;
} | {
    seniorKindergarten: null;
} {
    return value == StudentClass.grade1 ? {
        grade1: null
    } : value == StudentClass.grade2 ? {
        grade2: null
    } : value == StudentClass.grade3 ? {
        grade3: null
    } : value == StudentClass.grade4 ? {
        grade4: null
    } : value == StudentClass.grade5 ? {
        grade5: null
    } : value == StudentClass.grade6 ? {
        grade6: null
    } : value == StudentClass.grade7 ? {
        grade7: null
    } : value == StudentClass.juniorKindergarten ? {
        juniorKindergarten: null
    } : value == StudentClass.nursery ? {
        nursery: null
    } : value == StudentClass.seniorKindergarten ? {
        seniorKindergarten: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): {
    bhim: null;
} | {
    cash: null;
} | {
    googlePay: null;
} | {
    phonePe: null;
} {
    return value == PaymentMode.bhim ? {
        bhim: null
    } : value == PaymentMode.cash ? {
        cash: null
    } : value == PaymentMode.googlePay ? {
        googlePay: null
    } : value == PaymentMode.phonePe ? {
        phonePe: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentStatus): {
    complete: null;
} | {
    incompleteProfile: null;
} {
    return value == StudentStatus.complete ? {
        complete: null
    } : value == StudentStatus.incompleteProfile ? {
        incompleteProfile: null
    } : value;
}
function to_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<PaymentEntry>): Array<_PaymentEntry> {
    return value.map((x)=>to_candid_PaymentEntry_n1(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
